#!/bin/sh

if [ -f /Library/LaunchDaemons/ch.xxtou.hudservices.plist ]; then
    launchctl unload /Library/LaunchDaemons/ch.xxtou.hudservices.plist || true
fi

if [ -f /var/jb/Library/LaunchDaemons/ch.xxtou.hudservices.plist ]; then
    launchctl unload /var/jb/Library/LaunchDaemons/ch.xxtou.hudservices.plist || true
fi

exit 0